apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: gsp
stringData:
  ACCESS_KEY_ID: GOOG1EIXISYVLLPMFQU6Z5QTZXSOPEYN6G35ONUJJUNN3A3IBH2DOMO3FALUY
  SECRET_ACCESS_KEY: mINtsiP9RTPYSxstnXPf+frgP4m15x94WrSLssWI
  BUCKET_HOST: storage.googleapis.com
  BUCKET_NAME: gca-gsp-storage-bucket-gts
  BUCKET_PORT: "443"
  KAFKA_ADDR: infra-kafka-cp-kafka.infra.svc.cluster.local