apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: gauth
stringData:
  POSTGRES_ADDR: pgdb-gws-postgresql.infra.svc.cluster.local
  POSTGRES_USER: 	postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  DB_NAME: gauth
  gauth_pg_username: gauth_pg_user
  gauth_pg_password: Genesys1234
  gauth_redis_password: INSERT_REDIS_PASSWORD
  gauth_admin_username: gauth_admin_user
  gauth_admin_password: $2a$10$5LMxLuU110vqSV23VR0Rze6Y7z.0GkbJ/qRbXGQuK7C.h1I9Z4Oyi
  gauth_gws_client_id: external_api_client
  gauth_gws_client_secret: $2a$10$5LMxLuU110vqSV23VR0Rze6Y7z.0GkbJ/qRbXGQuK7C.h1I9Z4Oyi
  gauth_jks_keyPassword: Genesys1234 
  gauth_jks_keyStorePassword: Genesys1234
  LOCATION: /USW2