apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: gcxi
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  gcxi_db_host: pgdb-rpthist-postgresql.infra.svc.cluster.local
  gcxi_db_name: postgres
  tenant_id: 9350e2fc-a1dd-4c65-8d40-1f75a2e080dd
  tenant_sid: "100"
  gim_db_host: pgdb-rpthist-postgresql.infra.svc.cluster.local
  gim_db_name: gim
  gim_db_user: gim
  gim_db_pass: gim
  iwd_db_host: pgdb-rpthist-postgresql.infra.svc.cluster.local
  iwd_db_name: iwddm-100
  iwd_db_user: iwddm-100
  iwd_db_pass: Genesys1234
  GAUTH_CLIENT: gcxi_client
  GAUTH_KEY: secret
  LOCATION: USW2