apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: pulse
stringData:
  POSTGRES_ADDR: pgdb-rptrt-postgresql.infra.svc.cluster.local
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  POSTGRES_PORT: "5432"
  gws_ClientId: pulse_client
  gws_Client_Secret: secret
  redis_key: secret
  tenant_id: 9350e2fc-a1dd-4c65-8d40-1f75a2e080dd
  tenant_sid: "100"

