apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: deployment-secrets
  namespace: nexus
stringData:
  POSTGRES_ADDR: pgdb-dgt-postgresql.infra.svc.cluster.local
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: INSERT_POSTGRES_PASSWORD
  nexus_db_user: nexus
  nexus_db_password: nexus
  nexus_gws_client_id: nexus_client
  nexus_gws_client_secret: secret
  nexus_redis_password: INSERT_REDIS_PASSWORD
  tenant_id: 9350e2fc-a1dd-4c65-8d40-1f75a2e080dd
  tenant_locations: westus2
  tenant_primary_location: USW2
  tenant_sid: "100"